### ISSUE TITLE
photography page

### ISSUE THREAD

**Issue by arungsZoo** [dilawar/HippoApp#27]
[NewPage_Photography.pdf](https://github.com/dilawar/HippoApp/files/5212498/NewPage_Photography.pdf)

Photography team Admin should do
- [x] Should able to set a new theme.
- [x] Should be able set duration of each photography competition
- [x] from date to to date [stop/extend the duration at any point of time]
- [x] Duration for the voting phase [disable/alter the voting phase at any point of time]
- [x] Should be able to download the excel sheet of entries with participants names/ voting points.
- [x] Should be able to download photos in bulk.
- [ ] Judge’s choice /People choice phase can be automated. [We will discuss, instead of doing it manually]
- [x] If automated results , we shall be able to move to our repository. [We will discuss]

Participants
- [x] Participants should upload only three entries for each theme within only uploading phase.
- [x] Participants can alter description ,caption and re-upload the photo in uploading phase. Should be able to delete during uploading phase.
- [x] Participants should not upload/delete photo after uploading phase.
- [x] Participants should not vote his own entries.
- [x] Voting of Entries should be accurate, audience should not vote multiple times but can alter their vote during voting phase. Should not vote post voting phase.

Audience
- [x] Can view the photos [Privacy we need to discuss]
- [x] Can vote the photos during voting phase.
- [x] Can View Album of Themes.
- [x] Can view the results / Score.

Judging phase
- [ ] People choice votes should be calculate automatically by system. [we will discuss]
- [ ] Admin should be able to select the judges and the request should go judges and each judge should put their scores and submit [discuss]
- [ ] Post Judging phase score should calculate automatically. [we will discuss]

**Comment by dilawar** [comment]
@arungsZoo 
What would be the maximum size of image which can be uploaded on Hippo? 

Is there a restriction on the size of the image (widthxheight)? It can be resized when users are uploading the image.

**Comment by dilawar** [comment]
Also, is there a limit of number of entries a user can upload?

**Comment by photography2018** [comment]
@dilawar The current limit to the size each photo is 5 MB
(No restrictions on width&height)
One person (One mail id) can upload a maximum of 3 entries
-arun

**Comment by photography2018** [comment]
**Photography team Admin should do** 
→ Should able to set a new theme.
→ Should be able set duration of each photography competition 
       → from date to to date [stop/extend the duration at any point of time]
       → Duration for the voting phase [disable/alter the voting phase at any point of time]
       → Should be able to download the excel sheet of entries with participants names/ voting points.
       → Should be able to download photos in bulk. 
→ Judge’s choice /People choice phase can be automated. [We will discuss, instead of doing it manually]
→ If automated results , we shall be able to move to our repository. [We will discuss]

**Participants**  
 → Participants should upload only three entries for each theme within only uploading phase. 
 → Participants can alter description ,caption and re-upload the photo in uploading phase. Should be able to delete during **uploading phase**.
 → Participants should not upload/delete photo after uploading phase.
 → Participants should not vote his own entries.
 → Voting of Entries should be accurate, audience should not vote multiple times but can alter their vote during voting phase. Should not vote post voting phase.
  
**Audience**
   → Can view the photos [Privacy we need to discuss]
   → Can vote the photos during voting phase.
   → Can View Album of Themes.
    → Can view the results / Score. 

**Judging phase** 
→ People choice votes should be calculate automatically by system. [we will discuss]
→ Admin should be able to select the judges and the request should go judges and each judge should put their scores and submit [discuss]
→ Post Judging phase score should calculate automatically. [we will discuss]

**Comment by dilawar** [comment]
This is great @photography2018 . I'll try to finish a beta version by tomorrow.

**Comment by arungsZoo** [comment]
![Logo_Photography_Club_final](https://user-images.githubusercontent.com/71173426/93004992-49b29400-f56a-11ea-98a9-76d9407fdb42.jpg)
This is photography club logo @dilawar 
Need to ask comms office for permission to use the "blisc" label. For now, we can see where and how to arrange the logo in the webpage...

**Comment by dilawar** [comment]
Just pushed the alpha version to https://ncbs.res.in/hippo

Please login using `photography@ncbs.res.in` account. Click on `Photography Competition` page. On the top-right, you will see 'Admin' link. Click on it and add a theme. Set the other parameters.

Once a theme is set, it will start appearing the photography page and people are start uploading the image. Do upload a few test images and try the rating system.

Add the notes here if something is not right.

**Comment by arungsZoo** [comment]
@dilawar Since I forgot the password for photography, I logged in with my own email address. 
But surprisingly I could still add a new entry with my personal webmail id.

@Alok, could you mail me the password for the photography account..

**Comment by arungsZoo** [comment]
![Screenshot from 2020-09-15 03-34-27](https://user-images.githubusercontent.com/71173426/93143195-10faf200-f705-11ea-952d-edbe6406cb56.png)
Hi @dilawar I could not submit certain images. This is the error message that popped up.

**Comment by arungsZoo** [comment]
Few suggestions.. 
1. The description section is currently not displayed. Can we display it?
Instead of "Any other comment", we can put "**Description of the photograph (optional)**" 
[Optional, but displayed if entered]
2. After uploading, as of now there is option to change caption and even to delete the entry. Should we give these permissions? @photography2018 
3. The new images are being added "behind" the first image. I couldn't see any other uploaded entry apart from the first entry that I made. But if I delete the first entry, I can see the immediate next entry that I uploaded..

**Comment by arungsZoo** [comment]
I have left one entry there. Can someone check how is the rating system. 
(I can't vote for my pic! :p)

**Comment by arungsZoo** [comment]
@photography2018  The page title is **NCBS Photography Club** now.
 Should we keep **BLiSC Photography Competition**  ?

**Comment by photography2018** [comment]
Photography is not an email account. please assign admin to our 4 
individual mail id's.

**Comment by alok** [comment]
Stop messaging me, I don't know you

**Comment by dilawar** [comment]
> Few suggestions..
> 
>     1. The description section is currently not displayed. Can we display it?
>        Instead of "Any other comment", we can put "**Description of the photograph (optional)**"
>        [Optional, but displayed if entered]

Caption is always displayed. Any other comment is a note for admin etc. It is only available in the database and downloaded data. Descriptions might distract users from the photo. Short caption and image is a good format (IMHO).

>     2. After uploading, as of now there is option to change caption and even to delete the entry. Should we give these permissions? @photography2018

Only admin can do that as of now. User can only delete their own entries before voting phase starts. 

>     3. The new images are being added "behind" the first image. I couldn't see any other uploaded entry apart from the first entry that I made. But if I delete the first entry, I can see the immediate next entry that I uploaded..

Its a swiper. You should swipe left-rigth to see the new image. I will add helpful <> signs.

**Comment by dilawar** [comment]
# How to download data 

@photography2018 

Use this link https://ncbs.res.in/hippo/v1/pub/photographyclub_data . You can also optionally pass the competition id to the url e.g. https://ncbs.res.in/hippo/v1/pub/photographyclub_data/1 (first competition) to limit the results.

You will get a JSON file which has competion details and entries submitted by users. It also has anonymized voting information (list of stars). The images are as URL which you can use to download the data and save at your server appropriately. It is recommended to backup every month. Hippo sever is 100 GB in size which is plenty for time being. 

Except for the judge system, everything is implemented but not thoroughly tested.

**Comment by arungsZoo** [comment]
@dilawar I need to remove the blisc and ncbs logo elements from the club logo. I will share the new logo here before 8 pm today..

**Comment by arungsZoo** [comment]
Hi @dilawar can we include a line somewhere on top, saying "Swipe Left/Right to see all entries"
Also who updated the photo shouldn't be visible until judging phase is over. Can we have an admin option where we can enable/disable uploader visibility? Also can this have an independent nature for different themes? (Meaning we can disable name visibility for ongoing competition and enable for all past competitions? 
The duration of judging will vary, as often often judges are late to submit scores. So a manual control will be great for this..

**Comment by arungsZoo** [comment]
Hi @dilawar 
 I got an error msg while uploading the following image.
![Screenshot from 2020-09-15 16-47-04](https://user-images.githubusercontent.com/71173426/93204196-4fc79100-f773-11ea-9565-b7f017028d4d.png)

**Comment by dilawar** [comment]
> ![Screenshot from 2020-09-15 03-34-27](https://user-images.githubusercontent.com/71173426/93143195-10faf200-f705-11ea-952d-edbe6406cb56.png)
> Hi @dilawar I could not submit certain images. This is the error message that popped up.

This should have been fixed.

**Comment by arungsZoo** [comment]
![Logo_Photography_Club](https://user-images.githubusercontent.com/71173426/93223286-83afb000-f78d-11ea-9f6c-c475959b8e9b.jpg)

**Comment by arungsZoo** [comment]
Hi @dilawar I tried deleting the theme entry, "Test2", but it says 
You do not have permission to delete this entry.

**Comment by arungsZoo** [comment]
I couldn't remove your photo entries. It might be because you are admin?

**Comment by dilawar** [comment]
@arungsZoo Should be fixed now. Create a new issue for any problem big or small. It helps me keep the docs clean.

**Comment by arungsZoo** [comment]
Hi @dilawar Spoke with Alok. We may automate only People's choice category (PCC). 
There the score is calculated by multiplying **Total number of votes of one entry** to the **average votes it got**. Can we generate a results file for all the entries with their PCC score calculated?

**Comment by arungsZoo** [comment]
@dilawar I was able to submit a new entry to Hippo Photography page even after the submission deadline was over..

**Comment by photography2018** [comment]
@dilawar Please assign admin access to my id alokbb at ncbs dot res dot in , I am unable to view admin panel

**Comment by dilawar** [comment]
> @dilawar Please assign admin access to my id alokbb at ncbs dot res dot in , I am unable to view admin panel

Done. 

You should see `admin` link on the top right. 

![image](https://user-images.githubusercontent.com/895681/93601481-e9df4180-f9de-11ea-91a8-642ce16f9f7d.png)

**Comment by photography2018** [comment]
![Screenshot](https://user-images.githubusercontent.com/37058335/93603224-58bd9a00-f9e1-11ea-97ef-a1171902f063.png)

**Comment by dilawar** [comment]
#35 is fixed by https://github.com/dilawar/HippoApp/commit/c335962cc291ebec72b47856644965c601773cf8

**Comment by photography2018** [comment]
![but_enable_to_remove_option_is_hidden_behind_label](https://user-images.githubusercontent.com/37058335/93667251-01333300-faa2-11ea-8b2a-ad74a65cbe9b.png) -- unable to remove the photo since label is hiding the button

![json_error_while_uploading_second_photo](https://user-images.githubusercontent.com/37058335/93667256-0a240480-faa2-11ea-8eb1-47e3daf18bc8.png) --> json error while uploading second pic

**Comment by photography2018** [comment]
1.Please enable to option to pull to XLS along with submitter name , email id, voting  (sample XLSX attached)
2. Provide option to download images in bulk.
[XLSX.xlsx](https://github.com/dilawar/HippoApp/files/5249838/XLSX.xlsx)

**Comment by photography2018** [comment]
![Screenshot from 2020-09-19 18-09-13](https://user-images.githubusercontent.com/37058335/93667534-49535500-faa4-11ea-9159-7031778aa720.png) -- error while uploading 3rd pic
![Screenshot from 2020-09-19 18-09-36](https://user-images.githubusercontent.com/37058335/93667535-4b1d1880-faa4-11ea-936c-16be233c8472.png) -- removing one from the queue still giving same error

**Comment by dilawar** [comment]
Closed for the same reason as #34
