### ISSUE TITLE
Photography club logo?

### ISSUE THREAD

**Issue by dilawar** [dilawar/HippoApp#28]
__deleted__ 

This is photography club logo @dilawar 
Need to ask comms office for permission to use the "blisc" label. For now, we can see where and how to arrange the logo in the webpage...

_Originally posted by @arungsZoo in https://github.com/dilawar/HippoApp/issues/27#issuecomment-691550032_

**Comment by dilawar** [comment]
@arungsZoo followup here.

**Comment by arungsZoo** [comment]
Hi @dilawar Let's delete this logo from github as we don't have permission to use this version. I am unable to delete this from here..

**Comment by dilawar** [comment]
All right.
