### ISSUE TITLE
How to download data

### ISSUE THREAD

**Issue by dilawar** [dilawar/HippoApp#32]
# How to download data 

@photography2018 

Use this link https://ncbs.res.in/hippo/v1/pub/photographyclub_data . You can also optionally pass the competition id to the url e.g. https://ncbs.res.in/hippo/v1/pub/photographyclub_data/1 (first competition) to limit the results.

You will get a JSON file which has competion details and entries submitted by users. It also has anonymized voting information (list of stars). The images are as URL which you can use to download the data and save at your server appropriately. It is recommended to backup every month. Hippo sever is 100 GB in size which is plenty for time being. 

Except for the judge system, everything is implemented but not thoroughly tested.

_Originally posted by @dilawar in https://github.com/dilawar/HippoApp/issues/27#issuecomment-692542185_

**Comment by arungsZoo** [comment]
@dilawar  @photography2018
How to delete the Hippo entries after we have moved them to our repository?

**Comment by dilawar** [comment]
Currently you can't.

**Comment by dilawar** [comment]
Check with archives, if they are willing to keep an archive for the club. Sound like something worth preserving.

**Comment by arungsZoo** [comment]
Okay, I will ask Venkat

**Comment by arungsZoo** [comment]
Hi Dilawar, 
 Do you know any online platform where I can convert JSON into spreadsheet format?
@dilawar @photography2018

**Comment by dilawar** [comment]
1. Download the python script from https://raw.githubusercontent.com/dilawar/Scripts/master/hippo_photoclub_json_to_csv.py . Install pandas `python3 -m pip install pandas`.
2. `python3 hippo_photoclub_json_to_csv.py 8 > 8.csv`
where `8` is the id of competition. Open the 8.csv file in libreoffice.

Do you want to download the images as well? This file will have the URL of photocs.

**Comment by arungsZoo** [comment]
Thanks Dilawar, it worked. This is very useful..
Images we don't need to download now, as Hippo can be accessed from anywhere.
@dilawar 
@photography2018

**Comment by dilawar** [comment]
I am going to close it. If you need more help, reopen it or create a new ticket.
