### ISSUE TITLE
Score calculation

### ISSUE THREAD

**Issue by arungsZoo** [dilawar/HippoApp#34]
Hi @dilawar Spoke with Alok. We may automate only People's choice category (PCC).
There the score is calculated by multiplying Total number of votes of one entry to the average votes it got. Can we generate a results file for all the entries with their PCC score calculated?

**Comment by dilawar** [comment]
Any reference implementation or the  equation used?

**Comment by arungsZoo** [comment]
Total points = (Average Score) x (Number of non-zero votes)
Following page talks in detail..
https://github.com/photography2018/competition/blob/master/scoring.md

**Comment by dilawar** [comment]
This is invalid since page has been moved back to intranet.
