### ISSUE TITLE
After voting phase

### ISSUE THREAD

**Issue by arungsZoo** [dilawar/HippoApp#37]
@dilawar  @photography2018 
When voting phase ends, photos and votes are not shown anymore. 
Alok, We can keep photos visible till next competition starts?

**Comment by arungsZoo** [comment]
By mistake tagged another Alok again, sorry if you are coming here..

**Comment by dilawar** [comment]
This is fixed by commit https://github.com/dilawar/HippoApp/commit/1e665bffad20e25966fc2b6f5dc9b091dc01d0b4
