### ISSUE TITLE
after voting phase

### ISSUE THREAD

**Issue by arungsZoo** [dilawar/HippoApp#40]
Hi @dilawar  @photography2018
Can we keep showing the photographs even after the voting phase? 
Can we have an admin tool to enable/disable visibility of uploader's name at any point of time?

**Comment by dilawar** [comment]
Click on the finished competition to see all entries along with ratings.

Submitter identify is hidden till voting phase is over. I can make it visible to admin.

**Comment by arungsZoo** [comment]
Most times the judges take more time to judge, even after the public voting phase is over. So, there is more chances of them getting revealed with the uploader's identity.

**Comment by dilawar** [comment]
I see. One solution would be get rid of judges and let public decide. They get to vote on normal process anyway ☺️. 

Anyway, I see what I can do to accomodate their highnesses. 

⁣Sent from a handheld device, please pardon my brevity and tpyos. 

Get BlueMail for Android ​

**Comment by dilawar** [comment]
Another way to deal with it is to keep extending the voting end date till both phases are over. 

I'll add another fields 'judge_voting_end' which will take care of it.

⁣Sent from a handheld device, please pardon my brevity and tpyos. 

Get BlueMail for Android ​

**Comment by arungsZoo** [comment]
Hi @dilawar  Sorry I got trapped in some other things in between. 
Currently I am not able to load 'finished competitions' by clicking on it. (test theme 3). I am able to open 'August theme: Life during COVID'
Could you add the new field  'judge_voting_end' . After which the uploaders' identity can be revealed.

**Comment by dilawar** [comment]
Added `judge_voting_end_date` field.
