### ISSUE TITLE
Keeping of Photos

### ISSUE THREAD

**Issue by arungsZoo** [dilawar/HippoApp#42]
@dilawar 
How long/ how many themes can we store in Hippo up to?
Based on this, we will plan to move entries to other repository.
Also, how do you and when do you plan on purging entries from Hippo?

**Comment by dilawar** [comment]
Currently,

> How long/ how many themes can we store in Hippo up to?

There is no limit in the application. Its limited by the space available on the hippo server. The server size is 100GB with 80GB free space. That means it can store roughly ~12k photos. Assuming 20 entries per competition, 600 themes (100 years, 6 themes per year) before it runs out of space. 

> Based on this, we will plan to move entries to other repository.

See #32 and followup there. There is a simple URL which you can use to download entries.

> Also, how do you and when do you plan on purging entries from Hippo?

IT can remove old entries from `/run/srv/hippo/` directory after backup.
