### ISSUE TITLE
regarding new field for their highness

### ISSUE THREAD

**Issue by arungsZoo** [dilawar/HippoApp#43]
Hi @dilawar  
After voting phase ends, and judges' job is yet to be finished, there is a section showing 'finished competitions'. And when we go there we are still able to see participants' names.. It should be visible only when voting by judges are completed.

**Comment by dilawar** [comment]
Fixed in https://github.com/dilawar/hippo/commit/abd0465967c6203b43c27bec434d2dc6a00b4be9
