### ISSUE TITLE
intranet

### ISSUE THREAD

**Issue by arungsZoo** [dilawar/HippoApp#44]
@photography2018 @dilawar @ alokbb 
One of the picture that I had uploaded in hippo photography page, now appears in intranet photography page as multiple entries by multiple uploaders!
Any idea where the bug is?

**Comment by arungsZoo** [comment]
![image](https://user-images.githubusercontent.com/71173426/96139958-ffcc1d80-0f1c-11eb-830c-26044050bc9b.png)

example

**Comment by arungsZoo** [comment]
@dilawar  
We will start our contests from November onward.. hurray!

**Comment by dilawar** [comment]
Hippo does not touch intranet webserver. Someone from IT should be able to answer.

⁣Sent from a handheld device, please pardon my brevity and tpyos. 

Get BlueMail for Android ​

**Comment by arungsZoo** [comment]
Okay..
