### ISSUE TITLE
Final Touch ups

### ISSUE THREAD

**Issue by arungsZoo** [dilawar/HippoApp#45]
Hi @dilawar   Some final little touch ups before we take off!
1. Even after voting phase, on the Hippo photography page there is a sentence " Voting starts in 2 days, from (Sun) Oct 25 to (Sun) Oct 25 ". Can we remove this line 
2. The field "Any note for the participant" (present while making a new event): does this appear anywhere to the up-loader during participation?

@photography2018

**Comment by dilawar** [comment]
Will be back on Oct 31. Traveling.

**Comment by arungsZoo** [comment]
Oh okay, it's fine then, these are not that important changes
We are starting contest from Nov. 2
Happy travelling, stay safe

**Comment by dilawar** [comment]
I've fixed the 2. 
Comment again here when 1 appears again.

**Comment by arungsZoo** [comment]
'note for the participant' is visible now, 
But can we remove the title 'note for the participant' and show only the actual note?
(which is Rules and Guidelines as shown in hippo currently)

Also, Is it possible to enable a link in this note? (Which is  https://github.com/photography2018/competition/blob/master/Rules.md )

**Comment by dilawar** [comment]
- Enabled link.
- Removed 'note to participants'.

**Comment by photography2018** [comment]
Thanks Dilawar..
The link is correct, but for some reason I am not able to 'click' open it. But right click followed by choosing 'open link in new tab' works. I am not sure if this is issue from my system end or not..

**Comment by dilawar** [comment]
This is a issue with the app. I'll fix it soon.

**Comment by photography2018** [comment]
Cool!
