### ISSUE TITLE
error while uploading

### ISSUE THREAD

**Issue by arungsZoo** [dilawar/HippoApp#46]
@dilawar  Hi Dilawar
There seems to be an issue during photo submission. 
Nishant and I have tried uploading photos with low kb size, and they got uploaded. 
But when we tried uploading high sized photos (less than 5 MB), it showed an error message saying you can upload only one photo at  a time..  Can you look into this?
@photography2018

**Comment by dilawar** [comment]
Send me the image over email.

**Comment by dilawar** [comment]
Thanks for reporting. The hippo server was not configured to accept any upload of more than 2MB. I increased it to 6MB and changed the error message. It should work now. If it doesn't, please let me know.

**Comment by arungsZoo** [comment]
Sure, thank you
