### ISSUE TITLE
error while uploading

### ISSUE THREAD

**Issue by arungsZoo** [dilawar/HippoApp#47]
@dilawar 
One participant contacted saying he wasn't able to upload photo. 
I tried with his photo, it's not getting uploaded.
I have just emailed you the same.
@photography2018

**Comment by dilawar** [comment]
Related to #46. Sorry, my mistake. I modified the wrong `php.ini` to increase the upload limit. Fixed it now. You can see the configuration value here https://ncbs.res.in/hippo/v1/info/phpinfo . The upload limit to 10MB now but app does not allow more than 6MB. 

If this doesn't work, let me know.
