### ISSUE TITLE
option to remove entry

### ISSUE THREAD

**Issue by arungsZoo** [dilawar/HippoApp#50]
Hi Dilawar
Currently the photo submission phase is over, but the uploader can still remove his entries. 
Can we disable this?
@dilawar @photography2018

**Comment by dilawar** [comment]
It is by design. If the uploader wants to remove the entry, it's her right. Once voting phase is over, photos become read-only.

**Comment by arungsZoo** [comment]
Okay, but she has that right only till the submission phase ends. Once judging starts (now) it's inconvenient for the judges if few entries are removed or being removed. (Uploader can in this case write to the Team, who will then remove the concerned entry)

But since anyway we don't have voting right now (People's choice category is suspended) I will mark the voting phase as 'ended' so photos will be read only.
@dilawar  I selected the Voting Start and End dates as yesterday (22/11), but the previous error that we once sorted has occurred again, " Voting starts in 2 days, from (Sun) Nov 22 to (Sun) Nov 22 "
And I can still see the 'Remove' option. (Guess it's because of being admin)

@photography2018

**Comment by dilawar** [comment]
> @dilawar I selected the Voting Start and End dates as yesterday (22/11), but the previous error that we once sorted has occurred again, " Voting starts in 2 days, from (Sun) Nov 22 to (Sun) Nov 22 "
> And I can still see the 'Remove' option. (Guess it's because of being admin)

Just fixed it.

**Comment by arungsZoo** [comment]
Thanks Dilawar :-)

**Comment by dilawar** [comment]
Curently admin can remove any entry. 

If anyone wants to remove an entry after uploading phase is over, they can write to admin.
