### ISSUE TITLE
Suggestions/comments from User

### ISSUE THREAD

**Issue by arungsZoo** [dilawar/HippoApp#51]
Hi Dilawar
We got the following input from a user
*********************
"I noticed the Hippo page for the Photography club a bit hard to Navigate.
1. There is no Gallery view
2. The slider on the home page always shows the same image when launching. and it responds to drag and not click. Even the placement of the control handle is too far down and not dynamic according to image size. In short, there is no easy way to navigate across images on the home page.
3. The navigation after clicking the image through the overlay is good, but now it doesn't show the caption.
All these comments are based on viewing it on Firefox browser, with a 1920x1080 resolution screen."
**********************

>I guess the 3rd comment is most important. Can we show the caption after clicking the image?  (May be on the same panel where image serial number x/n is shown)
 And when we mark 'Judges evaluation as ended', can we show the uploader's name also there?

>The 2nd comment points out navigation issues, before clicking on an image (home page). Currently the blue arrow icons are not present, and only drag/keyboard arrow keys work. 

> If we can enable Gallery view as the default home view, then we can neglect the second point. And keep only Gallery view and Frame view (View after clicking on an image.)

@dilawar  @photography2018

**Comment by dilawar** [comment]
> And when we mark 'Judges evaluation as ended', can we show the uploader's name also there?

Yes. This feature is available.

**Comment by dilawar** [comment]
> The slider on the home page always shows the same image when launching. and it responds to drag and not click. Even the placement of the control handle is too far down and not dynamic according to image size. In short, there is no easy way to navigate across images on the home page.

Added navigation buttons > and < for desktop. On mobile, only pagination (dots at the bottom) appears. Images are randomized for each client.

> The navigation after clicking the image through the overlay is good, but now it doesn't show the caption.
   
Added caption in fullscreen mode.

**Comment by dilawar** [comment]
> If we can enable Gallery view as the default home view, then we can neglect the second point. And keep only Gallery view and Frame view (View after clicking on an image.)

If I enable that, I can't add 'vote of this image' in one click when people are browsing. For this competition, voting is disabled so you don't see that feature.

**Comment by arungsZoo** [comment]
> If I enable that, I can't add 'vote of this image' in one click when people are browsing. For this competition, voting is disabled so you don't see that feature.

You mean 'vote this image'? (during voting phase)
Sorry I didn't get that..

**Comment by dilawar** [comment]
Yes. User won't be able to vote for the image in one click. At least two clicks would be needed if I make the full screen 'gallery' as default view. 

Anyway this is very low on priority. If you come across a good site which has a better user interface, ping me on this thread.

**Comment by dilawar** [comment]
Closed for the same reason as #34
