### ISSUE TITLE
caption duplication ocassion 

### ISSUE THREAD

**Issue by arungsZoo** [dilawar/HippoApp#54]
Hi Dilawar,
When someone tries to upload an image with a caption that was used earlier in the same contest, the earlier image gets duplicated.
Can we enable a pop up message in such situations as below.
"Sorry, this caption is in use"

And not upload that entry unless the caption is unique..

Thanks
@photography2018
@dilawar

**Comment by dilawar** [comment]
Close of same reason as #34
